# Nested sequence

-
 - plums
 - grapes
-
  - Lemon
  - Ahhe

# Maps in yaml
student: Ousmane Sangary
role:
  job:
    - DevOps
    - MLOps
  age: 24

# same as
student: Ousmane Sangary
role: {job: [DevOps, MLOps], age: 24}

# !!pairs allow you to have pairs
pairMatch: !!pairs [job: student, job: teacher]

# !!set allows you to have unique values
names: !!set
  ? Ousmane
  ? Ousmane
  ? John
  ? Peter

## !!omap

# Anchors for reusing properties with &base
likings: &likes
  favFruits: Mango
  dislikes: guava

person1:
  name: John
  <<: *likes

person2:
  name: Peter
  <<: *likes
  dislikes: Samson

